INTENTS = {

    "show_duplicate_hostnames": [
        "show duplicate hostnames",
        "show duplicates",
        "find duplicates",
        "find duplicate hosts",
        "list duplicate hosts",
        "display duplicate hosts",
        "show hostname conflicts",
        "find hostname conflicts",
        "duplicates",
        "duplicate hosts",
        "show duplicated hostnames",
        "show duplicate systems",
        "show duplicate servers",
        "list hostname conflicts",
        "host conflicts",
        "duplicate hostname report",
        "find duplicate host names",
        "show host duplicates",
        "show duplicate machines",
        "list duplicate machines",
    ],

    "show_duplicate_ips": [
        "show duplicate ips",
        "find duplicate ips",
        "show ip conflicts",
        "duplicate ip addresses",
        "list duplicate ips",
        "show repeated ips",
        "find repeated ips",
        "duplicate ip report",
        "ip conflicts",
        "conflicting ips",
    ],

    "show_unhealthy_workloads": [
        "show unhealthy workloads",
        "find unhealthy workloads",
        "show unhealthy agents",
        "show workloads with health issues",
        "show workloads requiring attention",
        "list unhealthy systems",
        "show bad workloads",
        "find failed agents",
        "find unhealthy systems",
        "show unhealthy hosts",
    ],

    "show_stopped_agents": [
        "show stopped agents",
        "find stopped agents",
        "show inactive agents",
        "list stopped workloads",
        "show agents not running",
        "show down agents",
        "show workloads with stopped agents",
        "which agents are stopped",
        "find inactive workloads",
        "show stopped systems",
    ],

    "show_suspended_agents": [
        "show suspended agents",
        "find suspended agents",
        "list suspended workloads",
        "which agents are suspended",
        "show paused agents",
        "show suspended systems",
    ],

    "show_recent_changes": [
        "show recent changes",
        "show audit history",
        "show latest changes",
        "recent modifications",
        "show recent workload changes",
        "show recent updates",
        "latest audit entries",
        "what changed",
        "recent activity",
        "recent edits",
    ],

    "show_top_modified_workloads": [
        "show top modified workloads",
        "most modified workloads",
        "show heavily modified workloads",
        "show workloads with most changes",
        "top changed workloads",
        "most changed systems",
        "highest modified workloads",
    ],

    "show_dashboard_summary": [
        "show dashboard summary",
        "dashboard summary",
        "system summary",
        "workload summary",
        "show overview",
        "show dashboard",
        "environment summary",
        "infrastructure summary",
    ],

    "update_workload_status": [
        "change workload status",
        "change status",
        "set status",
        "set workload active",
        "set workload stopped",
        "activate workload",
        "deactivate workload",
        "change hostname status",
        "change agent status",
        "update workload status",
        "make workload active",
        "make workload stopped",
        "set agent active",
        "set agent stopped",
        "change conflict status",
    ],

    "rename_workload": [
        "rename workload",
        "rename hostname",
        "change hostname",
        "rename system",
        "rename server",
        "rename conflict02",
        "change workload name",
        "change hostname to",
    ],

    "suspend_workload": [
        "suspend workload",
        "suspend hostname",
        "pause workload",
        "pause hostname",
        "suspend conflict02",
        "suspend agent",
    ],

    "resume_workload": [
        "resume workload",
        "resume hostname",
        "resume conflict02",
        "enable workload",
        "restart workload",
        "unpause workload",
    ],

    "delete_workload": [
        "delete workload",
        "remove workload",
        "delete hostname",
        "remove hostname",
        "delete conflict02",
        "remove conflict02",
        "delete server",
        "remove server",
    ],
}